function showAccessories(vehicleType) {
    var accessoriesDiv = document.getElementById('accessories');
    console.log('vehicleType', vehicleType);
    accessoriesDiv.innerHTML = '';
    if (vehicleType === 'Motor') {
        accessoriesDiv.innerHTML = '<div class="row"><div class="col-sm-4"><div class="checkbox checkbox-inline"><input type="checkbox" id="helmet" name="accessories" value="Helmet"><label for="helmet">Helmet</label></div></div><div class="col-sm-4"><div class="checkbox checkbox-inline"><input type="checkbox" id="raincoat" name="accessories" value="Raincoat"><label for="raincoat">Raincoat</label></div></div><div class="col-sm-4"><div class="checkbox checkbox-inline"><input type="checkbox" id="securitylock" name="accessories" value="Security Lock"><label for="securitylock">Security Lock</label></div></div></div><div class="row"><div class="col-sm-4"><div class="checkbox checkbox-inline"><input type="checkbox" id="extrastorage" name="accessories" value="Extra Storage"><label for="extrastorage">Extra Storage</label></div></div><div class="col-sm-4"><div class="checkbox checkbox-inline"><input type="checkbox" id="handguard" name="accessories" value="Hand Guard"><label for="handguard">Hand Guard</label></div></div><div class="col-sm-4"><div class="checkbox checkbox-inline"><input type="checkbox" id="extramirrors" name="accessories" value="Extra Mirrors"><label for="extramirrors">Extra Mirrors</label></div></div></div><div class="row"><div class="col-sm-4"><div class="checkbox checkbox-inline"><input type="checkbox" id="engineguard" name="accessories" value="Engine Guard"><label for="engineguard">Engine Guard</label></div></div><div class="col-sm-4"><div class="checkbox checkbox-inline"><input type="checkbox" id="kneeguards" name="accessories" value="Knee Guards"><label for="kneeguards">Knee Guards</label></div></div><div class="col-sm-4"><div class="checkbox checkbox-inline"><input type="checkbox" id="elbowguards" name="accessories" value="Elbow Guards"><label for="elbowguards">Elbow Guards</label></div></div></div>';
    } else if (vehicleType === 'Mobil') {
        accessoriesDiv.innerHTML = '<div class="row" ><div class="col-sm-3"><div class="checkbox checkbox-inline"><input type="checkbox" id="airconditioner" name="airconditioner" value="1"><label for="airconditioner"> Air Conditioner </label></div></div><div class="col-sm-3"><div class="checkbox checkbox-inline"><input type="checkbox" id="powerdoorlocks" name="powerdoorlocks" value="1"><label for="powerdoorlocks"> Power Door Locks </label></div></div><div class="col-sm-3"><div class="checkbox checkbox-inline"><input type="checkbox" id="antilockbrakingsys" name="antilockbrakingsys" value="1"><label for="antilockbrakingsys"> AntiLock Braking System </label></div></div><div class="col-sm-3"><div class="checkbox checkbox-inline"><input type="checkbox" id="brakeassist" name="brakeassist" value="1"><label for="brakeassist"> Brake Assist </label></div></div></div ><div class="row"><div class="col-sm-3"><div class="checkbox checkbox-inline"><input type="checkbox" id="powersteering" name="powersteering" value="1"><label for="powersteering"> Power Steering </label></div></div><div class="col-sm-3"><div class="checkbox checkbox-inline"><input type="checkbox" id="driverairbag" name="driverairbag" value="1"><label for="driverairbag">Driver Airbag</label></div></div><div class="col-sm-3"><div class="checkbox checkbox-inline"><input type="checkbox" id="passengerairbag" name="passengerairbag" value="1"><label for="passengerairbag"> Passenger Airbag </label></div></div><div class="col-sm-3"><div class="checkbox checkbox-inline"><input type="checkbox" id="powerwindow" name="powerwindow" value="1"><label for="powerwindow"> Power Windows </label></div></div></div><div class="row"><div class="col-sm-3"><div class="checkbox checkbox-inline"><input type="checkbox" id="cdplayer" name="cdplayer" value="1"><label for="cdplayer"> CD Player </label></div></div><div class="col-sm-3"><div class="checkbox checkbox-inline"><input type="checkbox" id="centrallocking" name="centrallocking" value="1"><label for="centrallocking">Central Locking</label></div></div><div class="col-sm-3"><div class="checkbox checkbox-inline"><input type="checkbox" id="crashcensor" name="crashcensor" value="1"><label for="crashcensor"> Crash Sensor </label></div></div><div class="col-sm-3"><div class="checkbox checkbox-inline"><input type="checkbox" id="leatherseats" name="leatherseats" value="1"><label for="leatherseats"> Leather Seats </label></div></div></div>';
    }
}
